server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: productos-service
          uri: lb://productservice
          predicates:
            - Path=/productos/**
          filters:
            - RewritePath=/productos(?<segment>.*), /productos-api$\{segment}
        
        - id: ordenes-service
          uri: lb://orderservice
          predicates:
            - Path=/ordenes/**
          filters:
            - RewritePath=/ordenes(?<segment>.*), /orders-api$\{segment}
        
        - id: pagos-service
          uri: lb://paymentservice
          predicates:
            - Path=/pagos/**
          filters:
            - RewritePath=/pagos(?<segment>.*), /pagos-api$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: apigateway

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty]': DEBUG
